### ISSUE TITLE
Set up of Kanbanboard

### ISSUE THREAD

**Issue by DavidEspinoG** [sanieni6/catalogOfMyThings-Ruby-Group-Capstone-Project#15]
# Hello, dear code-reviewer
We are 3 people in this team @sanieni6 is going to be team member #2, @blueberry1312 team member #1  and @DavidEspinoG team member #3

[Kanbanboard](https://github.com/sanieni6/catalogOfMyThings-Ruby-Group-Capstone-Project/projects/1)

**Comment by Olamarx** [comment]
> # Hello, dear code-reviewer
> We are 3 people in this team @sanieni6 is going to be team member #2, @blueberry1312 team member #1 and @DavidEspinoG team member #3
> 
> [Kanbanboard](https://github.com/sanieni6/catalogOfMyThings-Ruby-Group-Capstone-Project/projects/1)

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Equal distribution of tasks ✔️
- All tasks added ✔️
- Good use of Kanban Board ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
